name: 'dbt_example'
version: '1.0.0'

profile: 'dbt_example'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_example:
    staging: # controla tudo que etá dentro da pasta staging
      schema: staging
      materialized: table #cria uma tabela materializada
      tags: ['staging']

    intermediate:
    matrerialized: ephemeral # não materializa a tabela
    tag: {intermediate}

    marts:
      schema: marts
      materizlized: table
      tag: {marts}
seeds:
  dbt_example:
    schema: seeds
    tags: ['seeds']
